version: '3'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
